<?php

namespace AppBundle\Repository;

/**
 * FileOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
