<?php

namespace AppBundle\Doctrine\Repository;

/**
 * FileUploadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileUploadRepository extends \Doctrine\ORM\EntityRepository
{
}
